// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oluso.Enterprise.Saml.EntityFramework;

#nullable disable

namespace Oluso.Enterprise.Saml.Migrations.Sqlite
{
    [DbContext(typeof(SamlDbContextSqlite))]
    partial class SamlDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Oluso.Enterprise.Saml.Entities.SamlServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedClaimsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssertionConsumerServiceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimMappingsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultRelayState")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EncryptAssertions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptionCertificate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameIdFormat")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonEditable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireSignedAuthnRequests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignAssertions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignResponses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SigningCertificate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SingleLogoutServiceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SsoBinding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EntityId")
                        .IsUnique();

                    b.ToTable("SamlServiceProviders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
